### ISSUE TITLE
Problems with deletion

### ISSUE THREAD

**Issue by hisnameisjimmy** [visfitness/reorderable#1]
I stumbled on your library and loved the simple implementation of drag and drop. However, I'm running into a challenge with deletion. Once I delete something and try and reorder, I consistently run into the following crash:
`Implicitly unwrapped nil value in ReorderableVStack.swift`

This doesn't occur for adding, just deletion. 

I am _very_ new to Swift, so it's possible I am doing something terribly misguided. But I threw together a quick demo just in case it helped articulate the issue better:
https://github.com/hisnameisjimmy/ReorderableDeleteTest

**Comment by GabRoyer** [comment]
Thanks for the bug report and the solid repro! Got a fix incoming.

**Comment by GabRoyer** [comment]
Fixed in 1.0.2

**Comment by hisnameisjimmy** [comment]
Amazing, confirmed fixed. Thank you for the incredibly fast turnaround!
